package game.net;

public enum PacketType {

	SERVER_FULL,
	SERVER_BANNED,
	CLIENT_JOIN,
	SERVER_ERROR,
	CLIENT_COMPANY_INFO,
	SERVER_COMPANY_INFO,
	SERVER_CLIENT_INFO,
	SERVER_NEED_PASSWORD,
	CLIENT_PASSWORD,
	SERVER_WELCOME,
	CLIENT_GETMAP,
	SERVER_WAIT,
	SERVER_MAP,
	CLIENT_MAP_OK,
	SERVER_JOIN,
	SERVER_FRAME,
	SERVER_SYNC,
	CLIENT_ACK,
	CLIENT_COMMAND,
	SERVER_COMMAND,
	CLIENT_CHAT,
	SERVER_CHAT,
	CLIENT_SET_PASSWORD,
	CLIENT_SET_NAME,
	CLIENT_QUIT,
	CLIENT_ERROR,
	SERVER_QUIT,
	SERVER_ERROR_QUIT,
	SERVER_SHUTDOWN,
	SERVER_NEWGAME,
	SERVER_RCON,
	CLIENT_RCON,
	END // Should ALWAYS be on the end of this list!! (period) [dz] really?
	
	
}
